# Generated by Django 4.2.5 on 2023-09-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kswap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="pictures_of_property",),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kswap.property"
                    ),
                ),
            ],
        ),
    ]
